---
redisSentinel:
  name: "redis"
  clusterSize: 3
  image: docker.io/ruo91/opstree-redis-sentinel-fedora
  tag: v8.0.2
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
    # - name:  Secret with Registry credentials
  redisSecret:
    secretName: "redis-secret"
    secretKey: "password"
  serviceType: ClusterIP
  resources:
    requests:
      #cpu: 2
      memory: 2Gi
    limits:
      #cpu: 2
      memory: 2Gi
  ignoreAnnotations: []
    # - "redis.opstreelabs.in/ignore"
  minReadySeconds: 0
  # -- Some fields of statefulset are immutable, such as volumeClaimTemplates.
  # When set to true, the operator will delete the statefulset and recreate it. Default is false.
  recreateStatefulSetOnUpdateInvalid: false

# Overwite name for resources
# name: ""

labels: {}
#   foo: bar
#   test: echo

redisSentinelConfig:
  redisReplicationName: "redis-replication"
  redisReplicationPassword:
    secretName: "redis-secret"
    secretKey: "password"
  masterGroupName: "redis"
  resolveHostnames: "redis.example.com"
  announceHostnames: "reids.example.com"
  redisPort: "6379"
  quorum: "2"
  parallelSyncs: "1"
  failoverTimeout: "180000"
  downAfterMilliseconds: "180000"

externalConfig:
  enabled: true
  data: |
    # Connection Management
    #protected-mode no
    maxclients 500000
    tcp-backlog 65535
    timeout 0
    tcp-keepalive 300
    
    # Memory Usage
    maxmemory 32gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 10
    
    # Performance / Timing
    hz 500
    #dynamic-hz yes
    
    # Latency tuning
    latency-monitor-threshold 5
    slowlog-log-slower-than 15000
    slowlog-max-len 1024
    
    # Append only file rewrite settings
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 128mb
    
    # Advanced fd tuning
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 128mb 64mb 60
    client-output-buffer-limit pubsub 256mb 64mb 60
    
    # Optimizing memory
    hash-max-ziplist-entries 1024
    hash-max-ziplist-value 256
    
    # When enabled, Redis evicts keys in a lazy (asynchronous) manner using background threads.
    # This reduces latency spikes during eviction by avoiding time-consuming deletions on the main thread.
    lazyfree-lazy-eviction yes
    
    # Enables lazy (asynchronous) deletion of expired keys.
    # Instead of removing keys synchronously when they expire, Redis defers the actual memory release to background threads.
    lazyfree-lazy-expire yes
    
    # When enabled, Redis performs DEL operations in a non-blocking way using background threads,
    # particularly for complex data types like lists, hashes, or sorted sets with many elements.
    lazyfree-lazy-server-del yes
    
    # Implementing Memory Defragmentation
    # Enables active memory defragmentation to reduce fragmentation in long-running Redis instances.
    # Helps reclaim fragmented memory and maintain performance stability over time.
    activedefrag yes
    
    # Multi-Threads
    io-threads-do-reads yes
    io-threads 4

externalService:
  enabled: true
  # annotations:
  #   foo: bar
  serviceType: NodePort
  port: 30010

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
  # -- extraLabels are added to the servicemonitor when enabled set to true
  extraLabels: {}
    # foo: bar
    # team: devops

redisExporter:
  enabled: false
  image: docker.io/ruo91/opstree-redis-exporter-fedora
  tag: "v1.74.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  env: []
    # - name: VAR_NAME
    #   value: "value1"
  securityContext: {}

initContainer:
  enabled: false
  image: ""
  imagePullPolicy: "IfNotPresent"
  resources: {}
    # requests:
    #   memory: "64Mi"
    #   cpu: "250m"
    # limits:
    #   memory: "128Mi"
    #   cpu: "500m"
  env: []
  command: []
  args: []

sidecars:
  name: "redis-tools"
  image: "docker.io/ruo91/opstree-redis-tools-fedora:v8.0.2"
  imagePullPolicy: "IfNotPresent"
  #resources:
  #  limits:
  #    cpu: "100m"
  #    memory: "128Mi"
  #  requests:
  #    cpu: "50m"
  #    memory: "64Mi"
  env: []
    # - name: MY_ENV_VAR
    #   value: "my-env-var-value"

priorityClassName: ""

nodeSelector:
  node-role.kubernetes.io/worker: ""

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

securityContext: {}

#affinity: {}
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists
          #values:
          #- ssd

tolerations: []
#tolerations:
#  - key: "node-role.kubernetes.io/worker"
#    operator: "Exists"
#    #value: "value"
#    effect: "NoSchedule"

serviceAccountName: "default"

TLS:
  ca: ca.key
  cert: tls.crt
  key: tls.key
  secret:
    secretName: ""

pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: null

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

env: []
  # - name: VAR_NAME
  #   value: "value1"
